spring.datasource.url=jdbc:postgresql://localhost:5433/poke_trade
spring.datasource.username=${POSTGRES_USER:poke}
spring.datasource.password=${POSTGRES_PASSWORD:poke}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.example.poketrade=DEBUG
