spring.application.name=poke-trade

spring.datasource.url=jdbc:postgresql://localhost:5433/poke_trade
spring.datasource.username=${POSTGRES_USER:poke}
spring.datasource.password=${POSTGRES_PASSWORD:poke}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
